install.packages("arules")
library(arules)
data(Groceries)
summary(Groceries)
rules=apriori(Groceries, parameter=list(support=0.006, confidence=0.08))
inspect(rules)
summary(rules)
rules=sort(rules, decreasing = TRUE, by="lift")
library(arulesViz)
plot(rules)
plot(rules, method="graph")
plot(rules, method="paracoord")

rules=eclat(Groceries, parameter=list(supp=0.06, maxlen=7))
inspect(rules)
summary(rules)
rules=sort(rules, decreasing = TRUE, by="lift")
plot(rules)

data=read.transactions(file.choose(),sep=",")
rules=apriori(data, parameter=list(support=0.0003, confidence=0.0008))
inspect(rules)
summary(rules)
rules=sort(rules, decreasing = TRUE, by="lift")
plot(rules)