---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

#Exercice1:
```{r}
#rm(list=ls())
N= 10000
U=runif(N)
X=c()
for (i in 1:length(U)){
  if (U[i]==0)
    X[i]=0
  else if (U[i]<=2/3)
    X[i]=(3/2)*U[i]
  else if (U[i]<=1)
    X[i]=2-sqrt(3-3*U[i])
  else X[i]=1
}
plot(X)
```

```{r}
d=seq(0,1,0.01)
d1=seq(1,2,0.01)
plot(ecdf(X))
lines(d,(2/3)*d,col='red')
lines(d1,(-1/3)+(4/3)*d1-((d1^2)/3),col='red')
```
```{r}
dd1=seq(min(X),1,0.01)
dd2=seq(1,max(X),0.01)
hist(X,freq = F)
lines(dd1,2/3*rep(1,length(dd1)),col='red')
lines(dd2,(4/3-(2/3)*dd2),col='red')
```

```{r}
moy=mean(X)
ect=sd(X)
cat("espérance : ",moy,"\n")
cat("écart-type : ",ect,"\n")
#Intervalle de conf à calculer
IC=c(moy-1.96*(ect/sqrt(N)),moy+1.96*(ect/sqrt(N)))
cat("Intervalle de confiance : ",IC,"\n")
```

#Exercice 2
```{r}
N=1000
r=0.05
sig=0.3
S0=100
K=105
t=10
Wt=rnorm(N,0,sqrt(t))
Y=pmax(S0*exp((r-sig^2/2)*t+sig*Wt) - K,0)
esp=mean(Y)
esp
C=exp(-r*t)*esp
C
```
```{r}
ec=sd(Y)*exp(-r*t)#pas(exp(-rt)² car racine de var->et)
ec
```
```{r}
Y1=pmax(S0*exp((r-sig^2/2)*t+sig*(-Wt)) - K,0)
```

```{r}
#Méthode variable antithétique
Y_t=(Y+Y1)/2
C1=mean(Y_t)*exp(-r*t)
ec1=sd(Y_t)*exp(-r*t)
C1
ec1
```



```{r}
plot(Y)
plot(Y_t)
IC2=c(C-1.96*(ec1/sqrt(N)),C+1.96*(ec1/sqrt(N)))
cat("Intervalle de confiance : ",IC2,"\n")
```
```{r}
d1=(1/(sig*sqrt(t)))*log(S0*exp(r*t)/K)+(sig/2)*sqrt(t)
d2=d1-sig*sqrt(t)
Cth=S0*pnorm(d1)-K*exp(-r*t)*pnorm(d2)
Cth
```

